name: mailgun
description: A Flutter package for sending email using Mailgun API
version: 0.0.4
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/flutter-mailgun

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mail: ^0.0.4
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
