name: dart_mailgun
description: A Dart package for interfacing with the Mailgun API
version: 0.1.3
homepage: https://github.com/beccauwu/flutter-mailgun

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.0
  intl: ^0.18.0
  bloc: ^8.1.0
dev_dependencies:
  test: ^1.22.2
